### PR TITLE
Waiting for code review

### PR DESCRIPTION
**Pull request by eapenzacharias**

### CODE REVIEW

**Review by JamesOkunlade — CHANGES_REQUESTED** [review]
Hello @eapenzacharias , @codingAngarita ,

This project like you have submitted for is a `Testing Your Ruby Code` project, I don't see you test anything or even install `Rspec`. Please check and ensure you have submitted under the right project title. Submit it under OOP project if its not a Testing project.

Request for another review when you're done.

Happy coding!

**Comment by angarita-dev** [comment]
Yep, I submitted under the wrong project title ups!

**Review by JamesOkunlade — CHANGES_REQUESTED** [review]
### Project Well Did.

Gameplays very well and the ability to choose to continue or quit after each round is ingenious as well.

One thing to do to improve your project however, If you could modify your code to make it accept the names of different player and let each player get assigned `X` or `O`.

Please do this and request another review.

Happy coding!

**Review by JamesOkunlade — APPROVED** [review]
Fantastic work!!

### The project looks real good now.

It meets the basic requirements to pass.

Merge to master, close pull request and fill the project completion form.

Good luck with your future project. :+1::+1:

**Pull request merged**
